spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:example}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: ${JWT_SECRET_KEY:a68bfc7195c4e0d8b54f482875799a81417b553413685f01f7689dc73945d6bb}

server:
  port: ${SERVER_PORT:8082}